spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.kafka.order.dto.CreateOrderCommand
        spring.json.trusted.packages: com.example.kafka.order.dto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: manual

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5433/kafka_demo
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
